#!/bin/bash
# vim: set ts=4:
set -o errexit

cd "$(dirname "$0")/.."

if [[ "$TRAVIS_PULL_REQUEST" != 'false' ]]; then
	echo 'This is a pull request, skipping deploy.'; exit 0
fi

if [[ -z "$BINTRAY_API_KEY" ]]; then
	echo '$BINTRAY_API_KEY is not set, skipping deploy.'; exit 0
fi

if [[ "$TRAVIS_BRANCH" != 'master' ]]; then
	echo 'This is not the master branch, skipping deploy.'; exit 0
fi

if [[ "${TRAVIS_BUILD_NUMBER}.2" != "$TRAVIS_JOB_NUMBER" ]]; then
	echo 'This is not the build job we are looking for, skipping deploy.'; exit 0
fi

echo '==> Deploying artifact to JFrog OSS Maven repository'
mvn deploy --settings .maven-bintray.xml -Dgpg.skip=true -DskipTests=true
